[[action]]
name = "BuyAxe"
cost = 2

[action.pre]
AtShop = true
HasMoney = true
[action.post]
HasAxe = true


[[action]]
name = "LootAxe"
cost = 1

[action.pre]
HasCorpse = true
[action.post]
HasAxe = true


[[action]]
name = "GoToShop"
cost = 1

[action.pre]
HasMoney = true
[action.post]
AtShop = true


[[action]]
name = "GetMoney"
cost = 1

[action.pre]
[action.post]
HasMoney = true
